# 头部菜单，title: link
menu:
  作者: /whoami
  分类: /categories
  归档: /archives
  标签: /tags
  #Github: https://github.com/Fechin
  #Twitter: https://twitter.com/FechinLi

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'bf23756d4cae28610d0a'
    # 应用秘钥
    clientSecret: '320297b950814346aefe5a3cd406b795321185e4'
    # issue仓库名
    repo: 'AtypeforFun.github.io'
    # Github名
    owner: 'AtypeforFun'
    # Github名
    admin: ['AtypeforFun']
    # Ensure uniqueness and length less than 50
    id: not real
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: coder

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
